# Generated by Django 3.2.9 on 2021-11-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_name', models.TextField(verbose_name='Название')),
                ('qr_link', models.TextField(verbose_name='Ссылка')),
                ('qr_img', models.ImageField(upload_to='media', verbose_name='Изображение')),
            ],
        ),
    ]
